### ISSUE TITLE
detection/detect 接口，不支持jpg格式的图片

### ISSUE THREAD

**Issue by PetersonLian** [FacePlusPlus/facepp-javascript-sdk#3]
如题。
当使用img参数，带上图片的Blob数据。
如果图片是jpg，则请求返回error code 1301，意思是图片格式不对。

**Comment by PetersonLian** [comment]
使用js api。  
调用方式  
    
     var faceApi = new FacePP('APPID', 'APPSECRETE', {
            apiURL: "http://apicn.faceplusplus.com"
        });    
    faceApi.request('detection/detect', {
                img: f.slice(0, f.size - 1),
            },function(err, result) {
                if (err) {
                    alert('' + err);
                    return;
                }
                alert(JSON.stringify(result));
            });    
其中f = e.target.files[0],是js File类型的实例。更具体点，就是`<input type="file">`的html 控件，我监听'change'事件，在事件响应中，我通过e.target.files[0]取得用户点击该控件并选择了的文件的File对象。  
问题在于： 我通过控件(`<input type="file">`)选择的图片文件。
1, 如果选择的图片文件是jpg格式的，则`faceApi.request`请求就会返回error code 1301的错误。
2, 如果选择的图片文件不是jpg格式的（只试了下Png的），则`faceApi.request`能返回成功的json数据。

**Comment by moon5ckq** [comment]
你的控件用了 enctype= multipart/form-data 么？

在 2015年5月22日 下午1:17，Peterson Lian <notifications@github.com>写道：

> 使用js api。
>
> 调用方式
>
>  var faceApi = new FacePP('APPID', 'APPSECRETE', {
>         apiURL: "http://apicn.faceplusplus.com"
>     });
> faceApi.request('detection/detect', {
>             img: f.slice(0, f.size - 1),
>         },function(err, result) {
>             if (err) {
>                 alert('' + err);
>                 return;
>             }
>             alert(JSON.stringify(result));
>         });
>
> 其中f = e.target.files[0],是js File类型的实例。更具体点，就是<input type="file">的html
> 控件，我监听'change'事件，在事件响应中，我通过e.target.files[0]取得用户点击该控件并选择了的文件的File对象。
>
> 问题在于： 我通过控件(<input type="file">)选择的图片文件。
> 1, 如果选择的图片文件是jpg格式的，则faceApi.request请求就会返回error code 1301的错误。
> 2, 如果选择的图片文件不是jpg格式的（只试了下Png的），则faceApi.request能返回成功的json数据。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FacePlusPlus/facepp-javascript-sdk/issues/3#issuecomment-104512913>
> .
>



-- 
   陈可卿,计05,清华大学
   Chen Keqing, CS&T05 ,Tsinghua

**Comment by brian14708** [comment]
是不是所有PNG都会有这个问题？可能是那张图片有问题。

**Comment by PetersonLian** [comment]
@moon5ckq @brian14708 不好意思，现在搞清楚了。是因为我的图片编码的问题，jpg编码出错了。jpg图片用的是png的编码数据，再上传，从而出错了。

**Comment by PetersonLian** [comment]
@moon5ckq @brian14708 建议[官网文档上](http://www.faceplusplus.com.cn/first_javascript_app/)的代码，能更新下，添加不传url参数，而是传img参数的示例。    
当初这个需求（自己上传img），我通过文档、qq交流群等总是找不到原因和方法，后来才自己摸索出来了。很是花时间。    
根本原因出在，当上传img参数的时候，参数对应的value应该是js中Blob类型的数据。  而我当初不知道，所以老是报错（不是1301）的错误。  
再次抱歉！
